// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hbekiucqstulmldcdknh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhiZWtpdWNxc3R1bG1sZGNka25oIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Njg3ODAxNjEsImV4cCI6MjA4NDM1NjE2MX0.nrbVjGajNZ60D3qBR1mJ52aK2L_1vM3vKYjnlCTmKZM";
// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);